---
title: "Donwload Financial Ratios from Yahoo Finance"
author: "Gabriel Foix"
output:
  html_document:
    df_print: paged
---

Process to extract an store all the Financial ratios from Yahoo Finance at the moment of execution.

Set of libraries to use
```{r message = FALSE, warning = FALSE}
library(magrittr)
library(jsonlite)
library(lubridate)
library(dplyr)
library(quantmod)
library(XML)
```


Source underlying utilities
```{r }
source('YahooFinanceUtils.R')
```

Read Companies List
```{r}
date <- gsub("-", "", today())
outputname <- paste0("FinRatiosYahoo", date, ".rds")
CompaniesList <- read.csv("CompanyList.20200703.csv", sep = ";")

```

Read the Financial Ratios as of `r today()`

```{r message = TRUE, warning = FALSE}
FinRatios <- getFinRatios(as.character(unique(CompaniesList$ticker)))

WrongTickers <- length(unique(CompaniesList$ticker)) - length(unique(FinRatios$Ticker))
message(paste("There are ", WrongTickers, "tickers wrong", sep = " ")

```


Adding Timestamp, country and Industry
```{r}
FinRatios <- FinRatios %>% 
  mutate(Date = date)

```

Writing out rds `r outputname`
```{r}
saveRDS(FinRatios, paste0("FinRatiosYahoo", date, ".rds"))
```

